context:
  name: essspectroscopy
  version: "25.9.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essspectroscopy-${{ version }}.tar.gz
  sha256: 4ac2da5de6e49d90041af311907e260b9cc0f50eca91e9feb057789403563945

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - essreduce >=25.07.0
    - python-graphviz >=0.20
    - pandas >=2
    - sciline >=25.4.1
    - scipp >=25.3.0
    - scippneutron >=24.8.0
    - scippnexus >=24.9.0
    - tof >=25.01.2

tests:
  - python:
      imports:
        - ess.spectroscopy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Spectroscopy data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/essspectroscopy
  homepage: https://scipp.github.io/essspectroscopy/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
