context:
  name: essspectroscopy
  version: "26.7.0"
  python_min: "3.11"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/essspectroscopy-${{ version }}.tar.gz
  sha256: a47d7691395c7602c4bf28efff02a907e101578d8b0c18f7b29afebd9b4bf3b2

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=77
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - essreduce >=26.6.0
    - python-graphviz >=0.20
    - pandas >=2.1.2
    - sciline >=25.4.1
    - scipp >=26.1.0
    - scippneutron >=25.11.2
    - scippnexus >=24.9.0
    - tof >=25.11.0

tests:
  - python:
      imports:
        - ess.spectroscopy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Spectroscopy data reduction for the European Spallation Source
  license: BSD-3-Clause
  license_file: LICENSE
  repository: https://github.com/scipp/ess/tree/main/packages/essspectroscopy
  homepage: https://scipp.github.io/ess/spectroscopy/

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
